farm_ecomm/cart/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'cart'

urlpatterns = [
	path(r'', views.cart_detail, name='cart_detail'),
	path(r'^/add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	path(r'^/remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),

]

farm_ecomm/customer/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns=[
        path('', views.cust, name='cust'),
        path('/home', views.cust, name='cust'),
        path('/fruits', views.fruits, name='fruits'),
        path('/vegetables', views.vegetables, name='vegetables'),
        path('/grains', views.grains, name='grains'),
        path('/others', views.others, name='others'),
        path('/poultry', views.poultry, name='poultry'),

]

farm_ecomm/farm_ecomm/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('customer', include('customer.urls')),
    path('farmer', include('farmer.urls')),
    path('cart', include('cart.urls',namespace='cart')),
    path('orders', include('orders.urls',namespace='orders')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

farm_ecomm/farmer/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns=[
        path('', views.farm, name='farm'),
        path('/home', views.farm, name='home'),
        path('/myproducts', views.myproducts, name='myproducts'),
        path('/add', views.add, name='add'),
        path('/account', views.account, name='account'),

]

farm_ecomm/orders/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'orders'

urlpatterns = [
	path(r'', views.od, name='od'),
	path(r'/myorder', views.myorder, name='myorder'),
	path(r'/checkout', views.order_create, name='order_create'),

]

farm_ecomm/cart/models.py
from django.db import models

# Create your models here.

farm_ecomm/customer/models.py
from django.db import models

# Create your models here.

farm_ecomm/farmer/models.py
from django.db import models

# Create your models here.
# class Fruit(models.Model):
#     seller = models.CharField(max_length=30)
#     prodname=models.CharField(max_length=30)
#     price=models.IntegerField()
#     image=models.ImageField(upload_to='pics')
#     class Meta:
#         db_table="fruit"
#
# class Vegetables(models.Model):
#     seller = models.CharField(max_length=30)
#     prodname=models.CharField(max_length=30)
#     price=models.IntegerField()
#     image=models.ImageField(upload_to='pics')
#     class Meta:
#         db_table="vegetables"
#
# class Grains(models.Model):
#     seller = models.CharField(max_length=30)
#     prodname=models.CharField(max_length=30)
#     price=models.IntegerField()
#     image=models.ImageField(upload_to='pics')
#     class Meta:
#         db_table="grains"
#
# class Poulatry(models.Model):
#     seller = models.CharField(max_length=30)
#     prodname=models.CharField(max_length=30)
#     price=models.IntegerField()
#     image=models.ImageField(upload_to='pics')
#     class Meta:
#         db_table="poulatry"
#
# class Other(models.Model):
#     seller = models.CharField(max_length=30)
#     prodname=models.CharField(max_length=30)
#     price=models.IntegerField()
#     image=models.ImageField(upload_to='pics')
#     class Meta:
#         db_table="other"

class Product(models.Model):
    cat=models.CharField(max_length=30)
    seller = models.CharField(max_length=30)
    prodname=models.CharField(max_length=30)
    price=models.IntegerField()
    image=models.ImageField(upload_to='pics')
    class Meta:
        db_table="product"

farm_ecomm/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity =forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

farm_ecomm/farmer/forms.py
from django import forms
from .models import *
#
#
# class FruitForm(forms.ModelForm):
#     class Meta:
#         model = Fruit
#         fields = "__all__"
#
#
# class VegetablesForm(forms.ModelForm):
#     class Meta:
#         model = Vegetables
#         fields = "__all__"
#
# class GrainsForm(forms.ModelForm):
#     class Meta:
#         model = Grains
#         fields = "__all__"
#
#
# class PoulatryForm(forms.ModelForm):
#     class Meta:
#         model = Poulatry
#         fields = "__all__"
#
#
# class OtherForm(forms.ModelForm):
#     class Meta:
#         model = Other
#         fields = "__all__"
#
#
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

farm_ecomm/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from farmer.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
	return redirect('cart:cart_detail')


def cart_remove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	return redirect('cart:cart_detail')


def cart_detail(request):
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
	return render(request, 'cart.html', {'cart': cart})

farm_ecomm/customer/views.py
from django.shortcuts import render
from farmer.models import *
from cart.forms import CartAddProductForm



# Create your views here.
def cust(request):
    name=request.session['username']
    return render(request,'customer.html',{'username':name})


def fruits(request):
    name = request.session['username']
    cart_f = CartAddProductForm()
    img = Product.objects.filter(cat='Fruits')    
    return render(request,'seeproducts.html',{'img':img,'cart_f':cart_f})


def vegetables(request):
    name = request.session['username']
    img = Product.objects.filter(cat='Vegetables')
    cart_f = CartAddProductForm()
    return render(request,'seeproducts.html',{'img':img,'cart_f':cart_f})


def grains(request):
    name = request.session['username']
    img = Product.objects.filter(cat='Grains')
    cart_f = CartAddProductForm()
    return render(request,'seeproducts.html',{'img':img,'cart_f':cart_f})



def poultry(request):
    name = request.session['username']
    img = Product.objects.filter(cat='Poulatry')

    cart_f = CartAddProductForm()
    return render(request,'seeproducts.html',{'img':img,'cart_f':cart_f})



def others(request):
    name = request.session['username']
    img = Product.objects.filter(cat='Other')
    cart_f = CartAddProductForm()
    return render(request,'seeproducts.html',{'img':img,'cart_f':cart_f})

farm_ecomm/farmer/views.py
from django.shortcuts import render,redirect
from .forms import *
from .models import *


# Create your views here.
def farm(request):
    name = request.session['username']
    return render(request,'farmer.html',{'username':name})


def myproducts(request):
    name = request.session['username']
    img = Product.objects.filter(seller=name,cat='Fruits')
    img2 = Product.objects.filter(seller=name, cat='Vegetables')
    img3 = Product.objects.filter(seller=name, cat='Grains')
    img4 = Product.objects.filter(seller=name,cat='Poulatry')
    img5 = Product.objects.filter(seller=name,cat='Other')
    return render(request, "myproducts.html", {"img": img,"img2": img2,"img3": img3,"img4": img4,"img5": img5})



def account(request):
    name = request.session['username']
    return render(request,'farmer.html',{'username':name})


def add(request):

    name = request.session['username']

    if request.method == "POST":

        f = {'seller': name, 'prodname': request.POST['prodname'], 'price': int(request.POST['price']),
                 'cat':request.POST['cat'],'image': request.FILES['image']}
        form2 = ProductForm(data=f, files=request.FILES)
        if form2.is_valid():
           form2.save()

        # if cat=='Fruits':
        #     f={'seller':name,'prodname':request.POST['prodname'],'price':int(request.POST['price']), 'image': request.FILES['image']}
        #     form = FruitForm(data=f,files=request.FILES)
        #     form2=ProductForm(data=f,files=request.FILES)
        #     if form.is_valid():
        #         form2.save()
        #         form.save()
        #
        #
        #
        # elif cat=='Vegetables':
        #     f = {'seller': name, 'prodname': request.POST['prodname'], 'price': int(request.POST['price']),
        #          'image': request.FILES['image']}
        #     form = VegetablesForm(data=f, files=request.FILES)
        #     form2 = ProductForm(data=f, files=request.FILES)
        #     if form.is_valid():
        #         form2.save()
        #         form.save()
        #
        #
        # elif cat=='Grains':
        #     f = {'seller': name, 'prodname': request.POST['prodname'], 'price': int(request.POST['price']),
        #          'image': request.FILES['image']}
        #     form = GrainsForm(data=f, files=request.FILES)
        #     form2 = ProductForm(data=f, files=request.FILES)
        #     if form.is_valid():
        #         form2.save()
        #         form.save()
        #
        #
        # elif cat=='Poulatry':
        #     f = {'seller': name, 'prodname': request.POST['prodname'], 'price': int(request.POST['price']),
        #          'image': request.FILES['image']}
        #     form = PoulatryForm(data=f, files=request.FILES)
        #     form2 = ProductForm(data=f, files=request.FILES)
        #     if form.is_valid():
        #         form2.save()
        #         form.save()
        #
        # else:
        #     f = {'seller': name, 'prodname': request.POST['prodname'], 'price': int(request.POST['price']),
        #          'image': request.FILES['image']}
        #     form = OtherForm(data=f, files=request.FILES)
        #     form2 = ProductForm(data=f, files=request.FILES)
        #     if form.is_valid():
        #         form2.save()
        #         form.save()
        #
        #
        #

    return render(request,'addproduct.html')

farm_ecomm/templates/addproduct.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Add Product</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'style3.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default rounded borders and increase the bottom margin */ 
    .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    }
    
    /* Remove the jumbotron's default bottom margin */ 
     .jumbotron {
      margin-bottom: 0;
    }
   
    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="home"><h3>Home</h3></a></li>
      </ul>     
    </div>
  </div>
</nav>
<div class="container">
<form enctype="multipart/form-data" method="post" id="fruit_form" novalidate="">
    {% csrf_token %}
    <div>
      <fieldset class="module aligned ">
        <div class="form-row field-prodname">
          <div>
            <label class="required" for="id_prodname">Prodname:</label>
            <input type="text" name="prodname" class="vTextField" maxlength="30" required="" id="id_prodname">
          </div>
        </div>
        <div class="form-row field-price">
          <div>
            <label class="required" for="id_price">Price:</label>
            <input type="number" name="price" class="vIntegerField" required="" id="id_price">
          </div>
        </div>
        <div class="form-row field-image">
          <div>
            <label class="required" for="id_image">Image:</label>
            <input type="file" name="image" accept="image/*" required="" id="id_image">
          </div>
        </div>
        <div class="form-group field-cat">
          <label for="cat">Category:</label>
          <select class="form-control" id="cat" name="cat">
            <option value="Fruits">Fruits</option>
            <option value="Vegetables">Vegetables</option>
            <option value="Grains">Grains</option>
            <option value="Poulatry">Poulatry</option>
            <option value="Other">Other</option>
          </select>
        </div>
        <div class="form-group form-button">
        <input type="submit" name="submit" id="submit" class="form-submit" value="submit" />
        </div>
      </fieldset>
    </div>
    <!-- <button type="button" class="btn btn-success">Submit</button> -->
</form>
</div>
</body>
</html>
 

farm_ecomm/templates/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>CART</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'style3.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default rounded borders and increase the bottom margin */ 
    .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    }
    
    /* Remove the jumbotron's default bottom margin */ 
     .jumbotron {
      margin-bottom: 0;
    }
   
    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="/customer"><h3>Home</h3></a></li>
      </ul>     
    </div>
  </div>
</nav>
<header><h2><b>Your Cart:</b></h2></header>

<table class="table table-striped table-hover">
    <thead style="background-color:#DCDCDC ">
        <tr>
            <th><h3><b>Image</b></h3></th>
            <th><h3><b>Product</b></h3></th>
            <th><h3><b>Quantity</b></h3></th>
            <th><h3><b>Remove</b></h3></th>
            <th><h3><b>Unit Price</b></h3></th>
            <th><h3><b>Price</b></h3></th>
        </tr>
    </thead>
    <tbody>
    {% for item in cart %}
        {% with product=item.product  %}
            <tr>
                <td>
                    <a href="{{ product.get__absolute_url }}">
                        <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 175px; width: auto">
                    </a>
                </td>
                <td><h3>{{ product.prodname }}</h3></td>
                <td>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {% csrf_token %}
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        <input type="submit" value="Update" class="btn btn-info">
                    </form>
                </td>
                <td>
                    <a href="{% url 'cart:cart_remove' product.id %}"><h3>Remove</h3></a>
                </td>
                <td><h3>Rs. {{ item.price }}</h3></td>
                <td><h3>Rs. {{ item.total_price }}</h3></td>
            </tr>
        {% endwith %}
    {% endfor %}
    <tr style="background-color: #DCDCDC">
        <td><h3><b>Total</b></h3></td>
        <td colspan="4"></td>
        <td colspan="num"><h3><b>Rs. {{ cart.get_total_price }}</b></h3></td>
    </tr>
    </tbody>
</table>
    <div class="col-md-12 bg-light text-right">
            <a href="{% url 'orders:od' %}" type="button" class="btn btn-success btn-lg float-right">PLACE ORDER</a>
    </div>
</body>
</html>
<!--#A9A9A9-->
<!--#DCDCDC-->

farm_ecomm/templates/checkout.html
{% load static %}
<!DOCTYPE html>
<body>
<link rel="stylesheet" href="{% static 'checkout.css' %}">
<div class="row">
    <div class="col-75">
      <div class="container">
        <form action="{% url 'orders:order_create' %}" method="POST">
          {% csrf_token %}
          <div class="row">
            <div class="col-50">
              <h3>Address</h3>
              <div class="col-50">
              <label ><i class="fa fa-user"></i> Full Name : {{username}}</label>
              </div>             
              <div class="col-50">
              <label for="phone"><i class="fa fa-envelope"></i> Phone</label>
              <input type="text" id="phone" name="phone">
              </div>
              <div class="col-50">
              <label for="address"><i class="fa fa-address-card-o"></i> Address</label>
              <input type="text" id="address" name="address">
              </div>
                <div class="col-50">
                  <label for="pincode">Pin</label>
                  <input type="text" id="pincode" name="pincode" placeholder="10001">
                </div>
            </div>
            </div>
            <div class="col-md-12 bg-light text-right">
                <input type="submit" class="btn btn-success btn-lg float-right" value="PLACE ORDER">
            </div>
        </form>  
      </div>
    </div>
</div>
</body>
</html>

farm_ecomm/templates/customer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Customer Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default rounded borders and increase the bottom margin */ 
    .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    }
    
    /* Remove the jumbotron's default bottom margin */ 
     .jumbotron {
      margin-bottom: 0;
    }
   
    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>       
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'orders:myorder' %}"><span class="glyphicon glyphicon-user"></span>{{username}}</a></li>
        <li><a href="/cart"><span class="glyphicon glyphicon-shopping-cart"></span> Cart</a></li>
        <li><a href="/home">Log out</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">    
  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-info">        
          <div class="panel-heading">FRUITS</div>
          <a href="/customer/fruits">
          <div class="panel-body"><img src="{% static 'fruits.jpg' %}" class="img-responsive" style="width:100%" alt="Image"></div>
        </a>
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-danger">
        <div class="panel-heading">VEGETABLES</div>
        <a href="/customer/vegetables">
        <div class="panel-body"><img src="{% static 'vegetables.jpg' %}" class="img-responsive" style="width:100%" alt="Image"></div>
        </a>
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-success">
        <div class="panel-heading">GRAINS</div>
        <a href="/customer/grains">
        <div class="panel-body"><img src="{% static 'g.jpg' %}" class="img-responsive" style="width:100%" alt="Image"></div>
        </a>
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel panel-warning">
        <div class="panel-heading">POULTARY</div>
        <a href="/customer/poultry">
        <div class="panel-body"><img src="{% static 'poultary.jpg' %}" class="img-responsive" style="width:100%" alt="Image"></div>
        </a>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="panel panel-warning">
        <div class="panel-heading">OTHERS</div>
        <a href="/customer/others">
        <div class="panel-body"><img src="{% static 'spices.jpg' %}" class="img-responsive" style="width:100%" alt="Image"></div>
        </a>
      </div>
    </div>
  </div>
</div>

</body>
</html>

farm_ecomm/templates/farmer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Farmer Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default rounded borders and increase the bottom margin */ 
    .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    }
    
    /* Remove the jumbotron's default bottom margin */ 
     .jumbotron {
      margin-bottom: 0;
    }
   
    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/farmer/account"><span class="glyphicon glyphicon-user"></span>{{username}}</a></li>
         <li><a href="/home">Log out</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">    
  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-primary">        
          <div class="panel-heading">LIST MY PRODUCTS</div>
          <a href="/farmer/myproducts">
          <div class="panel-body"><img src="{% static 'listproducts.png' %}" class="img-responsive" style="width:100%" alt="Image"></div>
          </a>
      </div>
    </div>
    <div class="col-sm-4"> 
      <div class="panel-body">
        <div class="panel-heading"></div>
        <!-- <a href="#"> -->
        <div class="panel-body"><img class="img-responsive" style="width:100%" ></div>
        <!-- </a> -->
      </div>
    </div>   
    <div class="col-sm-4"> 
        <div class="panel panel-danger">
          <div class="panel-heading">ADD PRODUCTS</div>
          <a href="/farmer/add">
          <div class="panel-body"><img src="{% static 'addproducts.png' %}" class="img-responsive" style="width:100%" alt="Image"></div>
          </a>
        </div>
      </div>    
  </div>
</div>

</body>
</html>

farm_ecomm/templates/seeproducts.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns:cart="http://www.w3.org/1999/xhtml">
<head>
  <title>Products</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'style3.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default rounded borders and increase the bottom margin */ 
    .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    }
    
    /* Remove the jumbotron's default bottom margin */ 
     .jumbotron {
      margin-bottom: 0;
    }
   
    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="home"><h3>Home</h3></a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">    
    {% for product in img %}
        {% if forloop.first %}<div class="row ">{% endif %}
            <div id="{{product.id}}" class="col-lg-4 col-md-4 col-12" >
        <div class="text-center mt-2">
            <img src="{{product.image.url}}"  class="img-thumbnail" alt="...">
            <h2 class="text-center" >{{product.prodname}}</h2>
            <h2 class="text-center" >Rs {{product.price}}</h2>
            <form method="post" action="{% url "cart:cart_add" product.id %}">
                {% csrf_token %}
                {{cart_f}}
            <input type="submit" class="btn btn-success" value="Add to cart">
            </form>
            </div>
            </div>
            {% if forloop.counter|divisibleby:3 %}
        </div>
        <div class=row>{% endif %}
        
            {% if forloop.last %}</div>{% endif %}
    
    {% endfor %}

</div>
</body>
</html>
 